CREATE TABLE habitacion (
    id_habitacion INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    es_zona_segura BOOLEAN NOT NULL
);

INSERT INTO habitacion (es_zona_segura, id_habitacion, descripcion, nombre) VALUES
(TRUE, 1, 'Entrada principal de la mansión. Aquí se encuentra la máquina dimensional averiada.', 'Vestíbulo Principal'),
(FALSE, 2, 'Biblioteca antigua llena de libros, sombras y conocimiento extraño.', 'Biblioteca'),
(FALSE, 3, 'Sala con motores, piezas metálicas y herramientas antiguas.', 'Sala de Máquinas'),
(TRUE, 4, 'Cocina cálida, ordenada y llena de aromas familiares.', 'Cocina'),
(FALSE, 5, 'Sala llena de radios, antenas y equipos de comunicación.', 'Sala de Comunicaciones'),
(FALSE, 6, 'Observatorio alto, silencioso y lleno de objetos extraños.', 'Observatorio'),
(FALSE, 7, 'Almacén lleno de cajas, piezas viejas y objetos olvidados.', 'Almacén'),
(FALSE, 8, 'Jardín interior con vegetación extraña de otros mundos.', 'Jardín Interior'),
(FALSE, 9, 'Sala circular llena de relojes que marcan horas distintas.', 'Sala del Reloj');


CREATE TABLE objeto (
    id_objeto INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    tipo_objeto VARCHAR(50) NOT NULL,
    valor_base INT NOT NULL
);

INSERT INTO objeto (valor_base, id_objeto, descripcion, nombre, tipo_objeto) VALUES
(500, 1, 'Un reloj roto que altera el tiempo.', 'Reloj Fragmentado', 'Temporal'),
(300, 2, 'Permite revelar las verdaderas intenciones de una persona.', 'Ojo Divino', 'Especial'),
(250, 3, 'Poción que obliga a decir la verdad.', 'Veritaserum', 'Pocion'),
(700, 4, 'Herramienta usada por Heinz para reparar tecnología.', 'Destornillador Dimensional', 'Herramienta'),
(900, 5, 'Fuente de energía antigua que Bip trajo desde su mundo.', 'Núcleo de Energía', 'Energia'),
(600, 6, 'Abre el baúl oculto del Observatorio.', 'Llave Negra', 'Llave'),
(100, 7, 'Permite estabilizar las señales de radio entre mundos.', 'reguladorRadio', 'Tecnologia'),
(400, 8, 'No apunta al norte. Reacciona ante anomalías dimensionales.', 'Brújula Extraña', 'Exploracion'),
(500, 9, 'Herramienta resistente usada para ajustar mecanismos pesados.', 'Llave Inglesa Reforzada', 'Herramienta'),
(1000, 10, 'Pieza inestable y clave para completar la máquina.', 'Regulador de Especia', 'Especial');


CREATE TABLE puerta (
    id_puerta INT AUTO_INCREMENT PRIMARY KEY,
    id_habitacion_origen INT NOT NULL,
    id_habitacion_destino INT NOT NULL,
    esta_bloqueada BOOLEAN NOT NULL DEFAULT FALSE,
    llave_requerida_id INT NULL,
    FOREIGN KEY (id_habitacion_origen) REFERENCES habitacion(id_habitacion) ON DELETE CASCADE,
    FOREIGN KEY (id_habitacion_destino) REFERENCES habitacion(id_habitacion) ON DELETE CASCADE,
    FOREIGN KEY (llave_requerida_id) REFERENCES objeto(id_objeto) ON DELETE SET NULL
);


CREATE TABLE objetos (
    id_instancia INT AUTO_INCREMENT PRIMARY KEY,
    id_habitacion INT NOT NULL,
    id_objeto INT NOT NULL,
    cantidad INT NOT NULL,
    estado VARCHAR(50) NOT NULL,
    FOREIGN KEY (id_habitacion) REFERENCES habitacion(id_habitacion) ON DELETE CASCADE,
    FOREIGN KEY (id_objeto) REFERENCES objeto(id_objeto) ON DELETE CASCADE
);

INSERT INTO objetos (cantidad, id_habitacion, id_instancia, id_objeto, estado) VALUES
(1, 9, 1, 1, 'Activo'),
(1, 4, 2, 2, 'Activo'),
(1, 2, 3, 3, 'Activo'),
(1, 1, 4, 4, 'Activo'),
(1, 7, 5, 5, 'Activo'),
(1, 6, 6, 6, 'Activo'),
(1, 5, 7, 7, 'Activo'),
(1, 8, 8, 8, 'Activo'),
(1, 3, 9, 9, 'Activo'),
(1, 6, 10, 10, 'Bloqueado');


CREATE TABLE eventos (
    id_eventos INT AUTO_INCREMENT PRIMARY KEY,
    categoria VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO eventos (id_eventos, categoria) VALUES
(1, 'Historia'),
(2, 'Entrega de objeto'),
(3, 'Revelacion'),
(4, 'Final');


CREATE TABLE evento (
    id_evento INT AUTO_INCREMENT PRIMARY KEY,
    descripcion_especifica TEXT NOT NULL,
    completado BOOLEAN NOT NULL DEFAULT FALSE,
    id_eventos INT NOT NULL,
    id_habitacion INT NOT NULL,
    FOREIGN KEY (id_eventos) REFERENCES eventos(id_eventos) ON DELETE CASCADE,
    FOREIGN KEY (id_habitacion) REFERENCES habitacion(id_habitacion) ON DELETE CASCADE
);


CREATE TABLE dialogo (
    id_dialogo INT AUTO_INCREMENT PRIMARY KEY,
    codigo_bloque VARCHAR(100) NOT NULL,
    orden INT NOT NULL,
    personaje VARCHAR(100) NOT NULL,
    texto TEXT NOT NULL,
    siguiente_bloque VARCHAR(100)
);

CREATE TABLE partida (
    id_partida INT AUTO_INCREMENT PRIMARY KEY,
    id_jugador BIGINT NOT NULL,
    bloque_actual VARCHAR(100) NOT NULL,
    linea_actual INT NOT NULL,
    terminada BOOLEAN NOT NULL DEFAULT FALSE,
    esperando_respuesta BOOLEAN NOT NULL DEFAULT FALSE
);


INSERT INTO dialogo (codigo_bloque, orden, personaje, texto, siguiente_bloque) VALUES
('INTRO_NOMBRE', 1, 'Sistema', '¿Cuál es tu nombre?', NULL),

('INTRO_DESPERTAR', 1, 'Narrador', 'Abres lentamente los ojos.', NULL),
('INTRO_DESPERTAR', 2, 'Narrador', 'El techo de madera es antiguo, el aire está cargado de polvo y un extraño silencio invade el lugar. No recuerdas cómo llegaste allí.', NULL),
('INTRO_DESPERTAR', 3, 'Narrador', 'Frente a ti se extiende un enorme vestíbulo. Varias puertas conducen hacia distintos pasillos de la mansión.', NULL),
('INTRO_DESPERTAR', 4, 'Narrador', 'A lo lejos distingues a dos personas conversando junto a una enorme máquina averiada.', 'VESTIBULO_INICIAL'),

('VESTIBULO_INICIAL', 1, 'Narrador', 'Una de ellas nota tu presencia y comienza a caminar hacia ti.', NULL),
('VESTIBULO_INICIAL', 2, 'Desconocido', 'Vaya... alguien más. ¿Quién eres? ¿Cómo llegaste aquí?', NULL),
('VESTIBULO_INICIAL', 3, 'Tú', 'Me llamo {jugador}... y la verdad... no lo sé.', NULL),
('VESTIBULO_INICIAL', 4, 'Desconocido', 'Entonces estamos igual. Mi nombre es Paul Atreides.', NULL),
('VESTIBULO_INICIAL', 5, 'Narrador', 'Te ofrece la mano.', NULL),
('VESTIBULO_INICIAL', 6, 'Paul', 'Créeme cuando digo que nadie aquí entiende realmente qué ocurrió.', NULL),
('VESTIBULO_INICIAL', 7, 'Paul', 'Él es Heinz Doofenshmirtz.', NULL),
('VESTIBULO_INICIAL', 8, 'Heinz', '¡Hola!... Espera... no toques ese cable... mejor no toques nada.', NULL),
('VESTIBULO_INICIAL', 9, 'Narrador', 'Se escucha una pequeña explosión.', NULL),
('VESTIBULO_INICIAL', 10, 'Heinz', '¡Todo está bajo control!', NULL),
('VESTIBULO_INICIAL', 11, 'Narrador', 'Paul sonríe con resignación.', NULL),
('VESTIBULO_INICIAL', 12, 'Paul', 'Distintas personas aparecieron en la mansión sin saber cómo llegaron. Heinz intenta reparar esta máquina encontrada en el Vestíbulo Principal.', NULL),
('VESTIBULO_INICIAL', 13, 'Heinz', '¡Tengo el mejor Destornillador Dimensional jamás construido!... Bueno... el único.', NULL),
('VESTIBULO_INICIAL', 14, 'Paul', 'Los demás habitantes encontraron objetos durante sus exploraciones. Si consigues reunirlos, Heinz intentará reparar la máquina.', NULL),
('VESTIBULO_INICIAL', 15, 'Paul', 'Ve al Almacén. Allí encontrarás a Bip.', 'ALMACEN_BIP'),
('ALMACEN_BIP', 1, 'Narrador', 'Al abrir la pesada puerta del almacén observas cajas, herramientas y objetos apilados por todas partes.', NULL),
('ALMACEN_BIP', 2, 'Narrador', 'Entre los montones de chatarra aparece una figura delgada.', NULL),
('ALMACEN_BIP', 3, 'Bip', 'Beep! ¿Eres amigo?', NULL),
('ALMACEN_BIP', 4, 'Tú', 'Eso espero. Me llamo {jugador}. Solo quiero encontrar la forma de salir de este lugar.', NULL),
('ALMACEN_BIP', 5, 'Narrador', 'Los ojos de Bip parecen iluminarse.', NULL),
('ALMACEN_BIP', 6, 'Bip', '¡Amigo! Bip también quiere salir.', NULL),
('ALMACEN_BIP', 7, 'Narrador', 'Da un pequeño salto de alegría.', NULL),
('ALMACEN_BIP', 8, 'Bip', '¿En qué ayudar?', NULL),
('ALMACEN_BIP', 9, 'Tú', 'Estamos intentando reparar una máquina. ¿Encontraste algo que pueda servir?', NULL),
('ALMACEN_BIP', 10, 'Narrador', 'Bip comienza a revisar una vieja mochila.', NULL),
('ALMACEN_BIP', 11, 'Narrador', 'Después de unos segundos saca un extraño dispositivo brillante.', NULL),
('ALMACEN_BIP', 12, 'Bip', 'Encontré esto hace mucho. Bip no sabe qué hace. Solo brillaba bonito.', NULL),
('ALMACEN_BIP', 13, 'Sistema', 'Has obtenido: Núcleo de Energía.', NULL),
('ALMACEN_BIP', 14, 'Bip', 'Si ayuda a amigo... Bip feliz.', NULL),
('ALMACEN_BIP', 15, 'Narrador', 'Vuelves al Vestíbulo Principal con el Núcleo de Energía.', 'VESTIBULO_POST_BIP'),
('VESTIBULO_POST_BIP', 1, 'Narrador', 'Regresas al Vestíbulo Principal.', NULL),
('VESTIBULO_POST_BIP', 2, 'Paul', 'Veo que Bip confió en ti.', NULL),
('VESTIBULO_POST_BIP', 3, 'Tú', 'Bip me pidió que les entregara esto.', NULL),
('VESTIBULO_POST_BIP', 4, 'Narrador', 'Le entregas el Núcleo de Energía a Heinz.', NULL),
('VESTIBULO_POST_BIP', 5, 'Heinz', '¡Sí! ¡Mi máquina ya parece un poco menos explosiva!', NULL),
('VESTIBULO_POST_BIP', 6, 'Narrador', 'Heinz instala el Núcleo de Energía en la máquina.', NULL),
('VESTIBULO_POST_BIP', 7, 'Narrador', 'La máquina emite un leve zumbido durante unos segundos.', NULL),
('VESTIBULO_POST_BIP', 8, 'Narrador', 'Las luces parpadean... pero vuelven a apagarse.', NULL),
('VESTIBULO_POST_BIP', 9, 'Heinz', 'Bueno... eso fue un avance. Creo.', NULL),
('VESTIBULO_POST_BIP', 10, 'Paul', 'Necesitamos encontrar las demás piezas.', NULL),
('VESTIBULO_POST_BIP', 11, 'Paul', 'Ve ahora a la Biblioteca. Allí encontrarás a Severus Snape.', 'BIBLIOTECA_SNAPE'),
('BIBLIOTECA_SNAPE', 1, 'Narrador', 'Llegas a la Biblioteca. Las estanterías llegan hasta el techo y el silencio es pesado.', NULL),
('BIBLIOTECA_SNAPE', 2, 'Desconocido', '¿Quién está ahí?', NULL),
('BIBLIOTECA_SNAPE', 3, 'Tú', 'Soy {jugador}.', NULL),
('BIBLIOTECA_SNAPE', 4, 'Severus Snape', 'Veo que eres alguien nuevo por aquí. Tienes la misma cara de perdido que el resto.', NULL),
('BIBLIOTECA_SNAPE', 5, 'Tú', 'Estamos reparando una máquina que podría sacarnos de este lugar. ¿Tienes algo que pueda ayudar?', NULL),
('BIBLIOTECA_SNAPE', 6, 'Severus Snape', 'No tengo nada que pueda ayudar a reparar una máquina muggle.', NULL),
('BIBLIOTECA_SNAPE', 7, 'Severus Snape', 'Pero puedo acompañarte. Quiero saber si realmente existe una salida.', NULL),
('BIBLIOTECA_SNAPE', 8, 'Sistema', 'Severus Snape se une al grupo.', NULL),
('BIBLIOTECA_SNAPE', 9, 'Narrador', 'Regresas al Vestíbulo Principal acompañado por Severus.', 'VESTIBULO_POST_SNAPE'),

('VESTIBULO_POST_SNAPE', 1, 'Paul', 'Entonces no tenía ninguna pieza útil...', NULL),
('VESTIBULO_POST_SNAPE', 2, 'Paul', 'No importa. Podemos buscar algo más.', NULL),
('VESTIBULO_POST_SNAPE', 3, 'Paul', 'Ve a la Sala de Comunicaciones. Maes Hughes trabajó con telecomunicaciones. Algo debe saber de frecuencias.', 'COMUNICACIONES_MAES'),

('COMUNICACIONES_MAES', 1, 'Narrador', 'Entras a una sala llena de radios antiguas, antenas y mapas pegados en la pared.', NULL),
('COMUNICACIONES_MAES', 2, 'Maes Hughes', '¡Alguien nuevo! ¿Cómo estás?', NULL),
('COMUNICACIONES_MAES', 3, 'Maes Hughes', '¿Quieres ver una foto de mi hermosa esposa y mi amada hija?', NULL),
('COMUNICACIONES_MAES', 4, 'Tú', 'Claro. Eres muy afortunado.', NULL),
('COMUNICACIONES_MAES', 5, 'Maes Hughes', '¡Lo soy! Son mi razón para volver a casa.', NULL),
('COMUNICACIONES_MAES', 6, 'Tú', 'Estamos reparando una máquina. ¿Tienes algo que pueda servir?', NULL),
('COMUNICACIONES_MAES', 7, 'Maes Hughes', 'Puede que sí. Tengo un Regulador de Ondas de Radio.', NULL),
('COMUNICACIONES_MAES', 8, 'Sistema', 'Has obtenido: reguladorRadio.', NULL),
('COMUNICACIONES_MAES', 9, 'Narrador', 'Vuelves al Vestíbulo Principal con el Regulador de Ondas de Radio.', 'VESTIBULO_POST_MAES'),

('VESTIBULO_POST_MAES', 1, 'Tú', 'Heinz, conseguí esto en la Sala de Comunicaciones.', NULL),
('VESTIBULO_POST_MAES', 2, 'Heinz', '¡Esto me servirá muchísimo!', NULL),
('VESTIBULO_POST_MAES', 3, 'Heinz', 'Con esto podremos regular las señales correspondientes a cada mundo.', NULL),
('VESTIBULO_POST_MAES', 4, 'Paul', 'Buen trabajo.', NULL),
('VESTIBULO_POST_MAES', 5, 'Paul', 'Ahora ve a la Sala de Máquinas. Allí encontrarás a Dominic Toretto.', 'SALA_MAQUINAS_DOMINIC'),

('SALA_MAQUINAS_DOMINIC', 1, 'Narrador', 'Llegas a una sala llena de motores, cables y herramientas antiguas.', NULL),
('SALA_MAQUINAS_DOMINIC', 2, 'Dominic', 'No te había visto por aquí. ¿Quién eres?', NULL),
('SALA_MAQUINAS_DOMINIC', 3, 'Tú', 'Me llamo {jugador}. Estoy intentando salir de esta mansión.', NULL),
('SALA_MAQUINAS_DOMINIC', 4, 'Dominic', 'Hay algo en ti. Me recuerdas a alguien que no se rendía aunque todo estuviera en su contra.', NULL),
('SALA_MAQUINAS_DOMINIC', 5, 'Dominic', '¿Qué buscas?', NULL),
('SALA_MAQUINAS_DOMINIC', 6, 'Tú', 'Estoy reuniendo piezas para reparar una máquina. Dicen que es la única forma de salir.', NULL),
('SALA_MAQUINAS_DOMINIC', 7, 'Dominic', 'No tengo mucho. Pero una buena herramienta puede marcar la diferencia.', NULL),
('SALA_MAQUINAS_DOMINIC', 8, 'Sistema', 'Has obtenido: Llave Inglesa Reforzada.', NULL),
('SALA_MAQUINAS_DOMINIC', 9, 'Dominic', 'Cuídala. No sirve de nada en las manos equivocadas.', NULL),
('SALA_MAQUINAS_DOMINIC', 10, 'Dominic', 'Buena suerte. Mientras tengas a alguien en quien confiar, siempre hay una forma de seguir adelante.', NULL),
('SALA_MAQUINAS_DOMINIC', 11, 'Narrador', 'Vuelves al Vestíbulo Principal con la Llave Inglesa Reforzada.', 'VESTIBULO_POST_DOMINIC'),

('VESTIBULO_POST_DOMINIC', 1, 'Tú', 'Dominic me entregó esta herramienta.', NULL),
('VESTIBULO_POST_DOMINIC', 2, 'Heinz', '¡Excelente! Esto sí parece algo que pertenece a una máquina.', NULL),
('VESTIBULO_POST_DOMINIC', 3, 'Heinz', 'Estoy logrando algo con todo lo que traes. Espero terminar pronto.', NULL),
('VESTIBULO_POST_DOMINIC', 4, 'Paul', 'Podrías ir al Observatorio.', NULL),
('VESTIBULO_POST_DOMINIC', 5, 'Paul', 'Allí hay un tipo extraño, pero puede que tenga algo útil.', 'OBSERVATORIO_JACK'),

('OBSERVATORIO_JACK', 1, 'Narrador', 'Subes hasta el Observatorio. El lugar está lleno de mapas, cristales y objetos antiguos.', NULL),
('OBSERVATORIO_JACK', 2, 'Jack', 'Espero que no hayas venido a quitarme el ron. Sería una pésima manera de empezar una amistad.', NULL),
('OBSERVATORIO_JACK', 3, 'Jack', 'Supongo que las presentaciones son lo correcto.', NULL),
('OBSERVATORIO_JACK', 4, 'Jack', 'Capitán Jack Sparrow. Aunque puedes llamarme Jack.', NULL),
('OBSERVATORIO_JACK', 5, 'Tú', 'Me llamo {jugador}. Solo quería saber si podrías ayudarme.', NULL),
('OBSERVATORIO_JACK', 6, 'Jack', 'Mucho gusto. Siempre es agradable conocer a alguien que todavía no intenta arrestarme.', NULL),
('OBSERVATORIO_JACK', 7, 'Tú', 'Estamos reparando una máquina para salir de aquí. ¿Tienes algo que pueda servir?', NULL),
('OBSERVATORIO_JACK', 8, 'Jack', 'Tengo un catalejo, un mapa bastante bonito y una llave.', NULL),
('OBSERVATORIO_JACK', 9, 'Jack', 'No tengo la menor idea de qué abre, pero las llaves suelen ser más importantes de lo que parecen.', NULL),
('OBSERVATORIO_JACK', 10, 'Sistema', 'Has obtenido: Llave Negra.', NULL),
('OBSERVATORIO_JACK', 11, 'Jack', 'Quizá abra una puerta. Quizá un cofre. O quizá nada. Lo divertido es descubrirlo.', NULL),
('OBSERVATORIO_JACK', 12, 'Narrador', 'Jack decide volver contigo al Vestíbulo Principal.', 'VESTIBULO_POST_JACK'),

('VESTIBULO_POST_JACK', 1, 'Narrador', 'Regresas al Vestíbulo Principal con Jack.', NULL),
('VESTIBULO_POST_JACK', 2, 'Heinz', 'Una llave misteriosa. No sé si sirve para la máquina, pero no pienso ignorarla.', NULL),
('VESTIBULO_POST_JACK', 3, 'Paul', 'Otro más que no nos ayuda directamente. Bueno, sigamos.', NULL),
('VESTIBULO_POST_JACK', 4, 'Paul', 'Ve al Jardín. Espero que Yelan siga ahí.', 'JARDIN_YELAN'),

('JARDIN_YELAN', 1, 'Narrador', 'Llegas al Jardín Interior acompañado por Jack.', NULL),
('JARDIN_YELAN', 2, 'Narrador', 'Yelan observa las flores y la vegetación como si estudiara un misterio.', NULL),
('JARDIN_YELAN', 3, 'Jack', '¡Yelan! ¡Al fin te encuentro!', NULL),
('JARDIN_YELAN', 4, 'Yelan', 'Jack. Pensé que seguirías buscando esa botella de ron que misteriosamente desapareció.', NULL),
('JARDIN_YELAN', 5, 'Jack', 'Una tragedia que aún me duele.', NULL),
('JARDIN_YELAN', 6, 'Yelan', 'No nos han presentado. Soy Yelan.', NULL),
('JARDIN_YELAN', 7, 'Tú', 'Un gusto. Soy {jugador}.', NULL),
('JARDIN_YELAN', 8, 'Yelan', 'Así que tú eres el recién llegado del que hablaba Paul.', NULL),
('JARDIN_YELAN', 9, 'Tú', 'Estamos reuniendo objetos para reparar una máquina. ¿Tienes algo que pueda servir?', NULL),
('JARDIN_YELAN', 10, 'Yelan', 'Puede que sí.', NULL),
('JARDIN_YELAN', 11, 'Sistema', 'Has obtenido: Brújula Extraña.', NULL),
('JARDIN_YELAN', 12, 'Jack', '¡Eh! Esa brújula es mía.', NULL),
('JARDIN_YELAN', 13, 'Yelan', 'Curioso. Porque estaba abandonada en un pasillo.', NULL),
('JARDIN_YELAN', 14, 'Jack', 'Técnicamente no la perdí. Solo decidí dejarla explorando por su cuenta.', NULL),
('JARDIN_YELAN', 15, 'Yelan', 'Claro. Igual que decidiste vaciar la botella.', NULL),
('JARDIN_YELAN', 16, 'Jack', 'De acuerdo. Consérvala. Si ayuda a sacarnos de aquí, prefiero verla en tus manos.', NULL),
('JARDIN_YELAN', 17, 'Narrador', 'Vuelves al Vestíbulo Principal con Jack y Yelan.', 'VESTIBULO_POST_YELAN'),

('VESTIBULO_POST_YELAN', 1, 'Tú', 'Heinz, conseguimos otra pieza.', NULL),
('VESTIBULO_POST_YELAN', 2, 'Heinz', '¡Una brújula! Perfecto.', NULL),
('VESTIBULO_POST_YELAN', 3, 'Heinz', 'No tengo idea de para qué sirve en la máquina, pero se ve importante.', NULL),
('VESTIBULO_POST_YELAN', 4, 'Paul', 'No existe una regla científica para eso.', NULL),
('VESTIBULO_POST_YELAN', 5, 'Heinz', 'Todavía no. Pero cuando esto funcione, la voy a escribir.', NULL),
('VESTIBULO_POST_YELAN', 6, 'Paul', 'Ahora tienes que ir a la Sala del Reloj. Ouro Kronii siempre está en ese lugar.', 'SALA_RELOJ_KRONII'),

('SALA_RELOJ_KRONII', 1, 'Narrador', 'Entras a una sala circular llena de relojes de todos los tamaños.', NULL),
('SALA_RELOJ_KRONII', 2, 'Narrador', 'Cada reloj marca una hora distinta, pero ninguno parece estar averiado.', NULL),
('SALA_RELOJ_KRONII', 3, 'Kronii', 'Curioso. Todos marcan horas diferentes y aun así ninguno está equivocado.', NULL),
('SALA_RELOJ_KRONII', 4, 'Kronii', 'Supongo que tú eres el recién llegado.', NULL),
('SALA_RELOJ_KRONII', 5, 'Tú', 'Sí. Me llamo {jugador}.', NULL),
('SALA_RELOJ_KRONII', 6, 'Kronii', 'Un gusto. Soy Ouro Kronii.', NULL),
('SALA_RELOJ_KRONII', 7, 'Tú', 'Estoy buscando objetos para reparar una máquina. ¿Tienes algo que pueda servir?', NULL),
('SALA_RELOJ_KRONII', 8, 'Narrador', 'Kronii observa uno de los relojes que sostiene entre sus manos.', NULL),
('SALA_RELOJ_KRONII', 9, 'Sistema', 'Has obtenido: Reloj Fragmentado.', NULL),
('SALA_RELOJ_KRONII', 10, 'Kronii', 'Puedes quedártelo. No afectará el funcionamiento del reloj.', NULL),
('SALA_RELOJ_KRONII', 11, 'Kronii', 'Hay algo más que deberías saber.', NULL),
('SALA_RELOJ_KRONII', 12, 'Kronii', 'He observado pequeños fragmentos del tiempo de quienes están aquí.', NULL),
('SALA_RELOJ_KRONII', 13, 'Kronii', 'Los fragmentos de todos son normales. Excepto los de Paul.', NULL),
('SALA_RELOJ_KRONII', 14, 'Tú', '¿Paul? Él ha estado ayudándonos desde que llegué.', NULL),
('SALA_RELOJ_KRONII', 15, 'Kronii', 'Lo sé. Y eso es precisamente lo que me inquieta.', NULL),
('SALA_RELOJ_KRONII', 16, 'Kronii', 'No te pido que desconfíes de él. Solo que no dejes de observarlo.', NULL),
('SALA_RELOJ_KRONII', 17, 'Narrador', 'Regresas al Vestíbulo Principal con el Reloj Fragmentado.', 'VESTIBULO_POST_KRONII'),

('VESTIBULO_POST_KRONII', 1, 'Tú', 'Heinz, conseguí otra pieza.', NULL),
('VESTIBULO_POST_KRONII', 2, 'Heinz', '¡Un reloj! Bueno... parte de uno. Excelente.', NULL),
('VESTIBULO_POST_KRONII', 3, 'Narrador', 'Heinz instala el Reloj Fragmentado en la máquina.', NULL),
('VESTIBULO_POST_KRONII', 4, 'Paul', 'Buen trabajo. Cada objeto nos acerca un poco más a terminarla.', NULL),
('VESTIBULO_POST_KRONII', 5, 'Narrador', 'Notas que observas a Paul más de lo habitual.', NULL),
('VESTIBULO_POST_KRONII', 6, 'Paul', '¿Ocurre algo?', NULL),
('VESTIBULO_POST_KRONII', 7, 'Tú', 'No. Solo estaba pensando.', NULL),
('VESTIBULO_POST_KRONII', 8, 'Paul', 'Si alguien te dijo algo sobre mí, prefiero que me lo preguntes directamente cuando llegue el momento.', NULL),
('VESTIBULO_POST_KRONII', 9, 'Heinz', '¿Terminamos el momento incómodo? Necesito que alguien sostenga este cable antes de que explote.', NULL),
('VESTIBULO_POST_KRONII', 10, 'Paul', 'Solo queda una persona. Ve a la Cocina. Raora Panthera debería estar allí.', 'COCINA_RAORA'),

('COCINA_RAORA', 1, 'Narrador', 'Al entrar en la cocina, un agradable aroma a pan recién horneado llena el ambiente.', NULL),
('COCINA_RAORA', 2, 'Raora', '¡Oh! Tenemos visita.', NULL),
('COCINA_RAORA', 3, 'Raora', 'Hola. Soy Raora Panthera. ¿Eres el nuevo?', NULL),
('COCINA_RAORA', 4, 'Tú', 'Sí. Soy {jugador}.', NULL),
('COCINA_RAORA', 5, 'Raora', 'Mucho gusto. Perdona si no fui a saludar antes. Cuando cocino, pierdo la noción del tiempo.', NULL),
('COCINA_RAORA', 6, 'Raora', 'Mientras haya ingredientes, nadie pasará hambre.', NULL),
('COCINA_RAORA', 7, 'Tú', 'Estamos reparando una máquina para salir de la mansión. Paul dijo que tal vez podrías ayudarnos.', NULL),
('COCINA_RAORA', 8, 'Raora', 'Creo que puedo, pero prefiero ir con ustedes.', NULL),
('COCINA_RAORA', 9, 'Raora', 'Hay algo que quiero comprobar antes de entregar lo que tengo.', NULL),
('COCINA_RAORA', 10, 'Narrador', 'Raora te acompaña de regreso al Vestíbulo Principal.', 'VESTIBULO_REUNION_FINAL'),

('VESTIBULO_REUNION_FINAL', 1, 'Narrador', 'Regresas al Vestíbulo Principal. Todos los habitantes de la mansión están reunidos alrededor de la máquina.', NULL),
('VESTIBULO_REUNION_FINAL', 2, 'Tú', '¿Qué ocurrió?', NULL),
('VESTIBULO_REUNION_FINAL', 3, 'Jack', 'Kronii apareció diciendo que todos debíamos reunirnos aquí.', NULL),
('VESTIBULO_REUNION_FINAL', 4, 'Kronii', 'Vi un pequeño fragmento del tiempo. Todos nosotros reunidos en esta habitación.', NULL),
('VESTIBULO_REUNION_FINAL', 5, 'Dominic', 'Eso fue suficiente para convencerme.', NULL),
('VESTIBULO_REUNION_FINAL', 6, 'Raora', 'Creo que ya es el momento.', NULL),
('VESTIBULO_REUNION_FINAL', 7, 'Tú', 'Raora... usa el Ojo Divino.', 'FINAL_OJO_DIVINO'),

('FINAL_OJO_DIVINO', 1, 'Narrador', 'Raora levanta lentamente el Ojo Divino.', NULL),
('FINAL_OJO_DIVINO', 2, 'Narrador', 'Una intensa luz recorre toda la habitación.', NULL),
('FINAL_OJO_DIVINO', 3, 'Narrador', 'Durante unos segundos nadie dice una palabra.', NULL),
('FINAL_OJO_DIVINO', 4, 'Narrador', 'Como si las mentiras dejaran de existir, todas las miradas se dirigen hacia una sola persona.', NULL),
('FINAL_OJO_DIVINO', 5, 'Narrador', 'Paul.', NULL),
('FINAL_OJO_DIVINO', 6, 'Severus Snape', 'Imperio.', NULL),
('FINAL_OJO_DIVINO', 7, 'Narrador', 'El cuerpo de Paul queda completamente inmóvil.', NULL),
('FINAL_OJO_DIVINO', 8, 'Severus Snape', 'Veritaserum.', NULL),
('FINAL_OJO_DIVINO', 9, 'Narrador', 'Snape obliga a Paul a beber unas gotas de la poción.', 'FINAL_CONFESION_PAUL'),

('FINAL_CONFESION_PAUL', 1, 'Bip', '¿Por qué hacer todo esto?', NULL),
('FINAL_CONFESION_PAUL', 2, 'Bip', '¿Cuál era el plan?', NULL),
('FINAL_CONFESION_PAUL', 3, 'Paul', 'Mi mundo ya estaba bajo mi control.', NULL),
('FINAL_CONFESION_PAUL', 4, 'Paul', 'Pero no era suficiente.', NULL),
('FINAL_CONFESION_PAUL', 5, 'Paul', 'Construí una máquina capaz de abrir portales entre dimensiones.', NULL),
('FINAL_CONFESION_PAUL', 6, 'Paul', 'Mi intención era conquistar otros mundos, uno por uno.', NULL),
('FINAL_CONFESION_PAUL', 7, 'Paul', 'Durante la primera prueba, la máquina falló.', NULL),
('FINAL_CONFESION_PAUL', 8, 'Paul', 'Los portales se volvieron inestables.', NULL),
('FINAL_CONFESION_PAUL', 9, 'Paul', 'En lugar de permitirme invadir otros mundos, comenzó a traer personas de distintas dimensiones hasta esta mansión.', NULL),
('FINAL_CONFESION_PAUL', 10, 'Paul', 'La máquina quedó dañada.', NULL),
('FINAL_CONFESION_PAUL', 11, 'Paul', 'Necesitaba que alguien reuniera nuevamente todas las piezas para repararla.', NULL),
('FINAL_CONFESION_PAUL', 12, 'Dominic', '¿Y después?', NULL),
('FINAL_CONFESION_PAUL', 13, 'Paul', 'Pensaba regresar solo.', NULL),
('FINAL_CONFESION_PAUL', 14, 'Bip', '¿Y amigo?', NULL),
('FINAL_CONFESION_PAUL', 15, 'Paul', 'Ustedes permanecerían aquí.', NULL),
('FINAL_CONFESION_PAUL', 16, 'Heinz', 'Todavía falta un componente.', NULL),
('FINAL_CONFESION_PAUL', 17, 'Heinz', 'Paul, ¿qué pieza falta para que la máquina funcione?', NULL),
('FINAL_CONFESION_PAUL', 18, 'Paul', 'El Regulador de Especia.', NULL),
('FINAL_CONFESION_PAUL', 19, 'Heinz', '¿Y dónde está?', NULL),
('FINAL_CONFESION_PAUL', 20, 'Paul', 'Dentro de un baúl en el Observatorio.', NULL),
('FINAL_CONFESION_PAUL', 21, 'Paul', 'Está cerrado con llave.', NULL),
('FINAL_CONFESION_PAUL', 22, 'Jack', '¿Te refieres a esta?', NULL),
('FINAL_CONFESION_PAUL', 23, 'Paul', 'Sí.', NULL),
('FINAL_CONFESION_PAUL', 24, 'Jack', '¡Ja! Sabía que guardaba esa llave por una razón.', NULL),
('FINAL_CONFESION_PAUL', 25, 'Yelan', 'Hace unas horas dijiste que no sabías para qué servía.', NULL),
('FINAL_CONFESION_PAUL', 26, 'Jack', 'Eso también puede formar parte de un buen plan.', NULL),
('FINAL_CONFESION_PAUL', 27, 'Dominic', 'Vamos antes de que cambie la historia otra vez.', 'OBSERVATORIO_BAUL'),

('OBSERVATORIO_BAUL', 1, 'Narrador', 'El grupo sube rápidamente al Observatorio.', NULL),
('OBSERVATORIO_BAUL', 2, 'Narrador', 'En una esquina encuentran un antiguo baúl de madera con un grueso candado.', NULL),
('OBSERVATORIO_BAUL', 3, 'Jack', 'Permítanme.', NULL),
('OBSERVATORIO_BAUL', 4, 'Narrador', 'Jack introduce la Llave Negra.', NULL),
('OBSERVATORIO_BAUL', 5, 'Narrador', 'Click.', NULL),
('OBSERVATORIO_BAUL', 6, 'Narrador', 'El candado se abre.', NULL),
('OBSERVATORIO_BAUL', 7, 'Sistema', 'Has obtenido: Regulador de Especia.', NULL),
('OBSERVATORIO_BAUL', 8, 'Jack', '¿Eso era todo? Esperaba al menos otra botella de ron.', NULL),
('OBSERVATORIO_BAUL', 9, 'Narrador', 'El grupo regresa al Vestíbulo Principal.', 'VESTIBULO_FINAL'),

('VESTIBULO_FINAL', 1, 'Heinz', '¡Eso era! ¡Sabía que faltaba algo importante!', NULL),
('VESTIBULO_FINAL', 2, 'Narrador', 'Heinz instala cuidadosamente el Regulador de Especia en la máquina.', NULL),
('VESTIBULO_FINAL', 3, 'Narrador', 'Los engranajes comienzan a girar.', NULL),
('VESTIBULO_FINAL', 4, 'Narrador', 'La máquina vibra y una intensa luz azul invade el vestíbulo.', NULL),
('VESTIBULO_FINAL', 5, 'Heinz', '¡Funcionó!', NULL),
('VESTIBULO_FINAL', 6, 'Narrador', 'Un portal comienza a abrirse frente al grupo.', NULL),
('VESTIBULO_FINAL', 7, 'Dominic', 'Él va primero.', NULL),
('VESTIBULO_FINAL', 8, 'Narrador', 'Paul atraviesa el portal atado y sin ningún objeto.', NULL),
('VESTIBULO_FINAL', 9, 'Heinz', 'Perfecto. El portal permanece estable.', NULL),
('VESTIBULO_FINAL', 10, 'Heinz', 'Ahora sí. Es hora de volver a casa.', 'PORTAL'),

('PORTAL', 1, 'Narrador', 'Uno a uno, todos atraviesan el portal.', NULL),
('PORTAL', 2, 'Jack', 'Jack se despide levantando su sombrero.', NULL),
('PORTAL', 3, 'Yelan', 'Yelan hace un pequeño gesto con la mano.', NULL),
('PORTAL', 4, 'Raora', 'Raora desea que todos lleguen sanos a casa.', NULL),
('PORTAL', 5, 'Bip', 'Beep! Bip nunca olvidará a sus amigos.', NULL),
('PORTAL', 6, 'Maes Hughes', 'Maes sonríe pensando en su familia.', NULL),
('PORTAL', 7, 'Severus Snape', 'Snape cruza el portal sin decir demasiado.', NULL),
('PORTAL', 8, 'Kronii', 'Al final, el tiempo encontró el camino correcto.', NULL),
('PORTAL', 9, 'Narrador', 'Kronii cruza el portal.', 'EPILOGO'),

('EPILOGO', 1, 'Narrador', 'Solo quedas tú frente a la máquina.', NULL),
('EPILOGO', 2, 'Narrador', 'Miras por última vez la mansión que reunió a personas de mundos completamente distintos.', NULL),
('EPILOGO', 3, 'Narrador', 'Respiras hondo.', NULL),
('EPILOGO', 4, 'Narrador', 'Das un paso al frente.', NULL),
('EPILOGO', 5, 'Narrador', 'Y atraviesas el portal.', NULL),
('EPILOGO', 6, 'Sistema', 'FIN.', NULL);